### ISSUE TITLE
First selection always does not change the timezone - works perfectly when select again

### ISSUE THREAD

**Issue by jaspreetsingh2701** [mishguruorg/angular-timezone-selector#70]
Hello,
Following is the snippet of code:
```
<div>
 <timezone-selector 
   display-utc="true" 
   sort-by="offset" 
   show-local="true" 
   set-local="true"
   ng-model="timezone">
</div>
```

when I selects the option from dropzone, the changes doesn't reflect back on UI but when I select again some other option then it works perfectly fine.

Any ideas?

Thanks in Advance

**Comment by raksit31667** [comment]
Hi, @jaspreetsingh2701

As you can see from these LOC

```javascript
.directive('timezoneSelector', ['_', 'moment', 'timezoneFactory', 'zoneToCC', 'CCToCountryName', function (_, moment, timezoneFactory, zoneToCC, CCToCountryName) {
    return {
      restrict: 'E',
      replace: true,
      template: '<select style="min-width:300px;"></select>',
      scope: {
        ngModel: '=',
        translations: '='
      },
```

`<select>` doesn't bind with `ng-options`, that's why it doesn't work for the first time we select

**Comment by fireole** [comment]
it is because if you use angular 1.6.0 or above it is breaking.  It will will work with angularjs version 1.5.9 and below.  

in the plunkr example , just change the angular version from https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.8/angular.min.js   to https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.0/angular.min.js or above and will break it
